name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        go:
          - '1.21'
          - '1.20'
          - '1.18'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: install mecab and neologd
        run: |
          sudo apt-get update
          sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file
          git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
          cd mecab-ipadic-neologd
          sudo ./bin/install-mecab-ipadic-neologd -n -y
          echo "dicdir = $(mecab-config --dicdir)/mecab-ipadic-neologd" | sudo tee /etc/mecabrc
      - name: test
        shell: bash
        run: |
          export CGO_CFLAGS="$(mecab-config --cflags) -I/usr/include"
          export CGO_LDFLAGS="$(mecab-config --libs)"
          ./go.test.sh
      - name: upload coverage report
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,GO
        env:
          OS: ${{ matrix.os }}
          GO: ${{ matrix.go }}
